[package]
name = "clap-cli1"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
randomizer = "0.1.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
t_bang = "0.1.4"
